package com.algaworks.algashop.ordering.domain.model.exception.enums;

import lombok.RequiredArgsConstructor;

import static com.algaworks.algashop.ordering.domain.model.exception.ErrorMessages.*;

@RequiredArgsConstructor
public enum OrderReason implements ReasonMessage {

    NO_ITEMS(ERROR_ORDER_CANNOT_BE_PLACED_HAS_NO_ITEMS),
    NO_SHIPPING_INFO(ERROR_ORDER_CANNOT_BE_PLACED_HAS_NO_SHIPPING_INFO),
    NO_BILLING_INFO(ERROR_ORDER_CANNOT_BE_PLACED_HAS_NO_BILLING_INFO),
    INVALID_SHIPPING_COST(ERROR_ORDER_CANNOT_BE_PLACED_INVALID_SHIPPING_COST),
    INVALID_EXPECTED_DELIVERY_DATE(ERROR_ORDER_CANNOT_BE_PLACED_INVALID_DELIVERY_DATE),
    NO_PAYMENT_METHOD(ERROR_ORDER_CANNOT_BE_PLACED_HAS_NO_PAYMENT_METHOD),
    NO_ORDER_DELIVERY_DATE_CANNOT_BE_IN_THE_PAST(ERROR_ORDER_DELIVERY_DATE_CANNOT_BE_IN_THE_PAST),
    NO_ORDER_STATUS_CANNOT_BE_CHANGED(ERROR_ORDER_STATUS_CANNOT_BE_CHANGED),
    NO_ORDER_DOES_NOT_CONTAIN_ITEM(ERROR_ORDER_DOES_NOT_CONTAIN_ITEM),
    NO_PRODUCT_IS_OUT_OF_STOCK(ERROR_PRODUCT_IS_OUT_OF_STOCK),
    NO_ORDER_CANNOT_BE_EDITTED(ERROR_ORDER_CANNOT_BE_EDITTED),
    INVALID_SHOPPING_CART_ITEM_INCOMPATIBLE_PRODUCT(ERROR_SHOPPING_CART_ITEM_INCOMPATIBLE_PRODUCT),
    NO_SHOPPING_CART_DOES_NOT_CONTAIN_ITEM(ERROR_SHOPPING_CART_DOES_NOT_CONTAIN_ITEM),
    NO_SHOPPING_CART_IS_NOT_AVAILABLE(ERROR_SHOPPING_CART_NOT_AVAILABLE);

    private final String template;

    @Override
    public String format(Object... args) {
        return String.format(template, args);
    }

}
