package com.algaworks.algashop.ordering.domain.exception.enums;

import lombok.RequiredArgsConstructor;

import static com.algaworks.algashop.ordering.domain.exception.ErrorMessages.*;

@RequiredArgsConstructor
public enum ReasonMessageEnum implements ReasonMessage {

    NO_ITEMS(ERROR_ORDER_CANNOT_BE_PLACED_HAS_NO_ITEMS),
    NO_SHIPPING_INFO(ERROR_ORDER_CANNOT_BE_PLACED_HAS_NO_SHIPPING_INFO),
    NO_BILLING_INFO(ERROR_ORDER_CANNOT_BE_PLACED_HAS_NO_BILLING_INFO),
    NO_PAYMENT_METHOD(ERROR_ORDER_CANNOT_BE_PLACED_HAS_NO_PAYMENT_METHOD),
    NO_ORDER_DELIVERY_DATE_CANNOT_BE_IN_THE_PAST(ERROR_ORDER_DELIVERY_DATE_CANNOT_BE_IN_THE_PAST),
    NO_ORDER_STATUS_CANNOT_BE_CHANGED(ERROR_ORDER_STATUS_CANNOT_BE_CHANGED),
    NO_ORDER_DOES_NOT_CONTAIN_ITEM(ERROR_ORDER_DOES_NOT_CONTAIN_ITEM),
    NO_PRODUCT_IS_OUT_OF_STOCK(ERROR_PRODUCT_IS_OUT_OF_STOCK),
    NO_ORDER_CANNOT_BE_EDITTED(ERROR_ORDER_CANNOT_BE_EDITTED),
    INVALID_SHOPPING_CART_ITEM_INCOMPATIBLE_PRODUCT(ERROR_SHOPPING_CART_ITEM_INCOMPATIBLE_PRODUCT),
    NO_SHOPPING_CART_DOES_NOT_CONTAIN_ITEM(ERROR_SHOPPING_CART_DOES_NOT_CONTAIN_ITEM),
    NO_SHOPPING_CART_IS_NOT_AVAILABLE(ERROR_SHOPPING_CART_NOT_AVAILABLE),
    NO_ORDER_NOT_BELONGS_TO_CUSTOMER(ERROR_ORDER_NOT_BELONS_TO_CUSTOMER),
    NO_CUSTOMER_NOT_FOUND(ERROR_CUSTOMER_NOT_FOUND),
    CUSTOMER_ALREADY_HAVE_SHOPPING_CART_EXIST(ERROR_CUSTOMER_ALREADY_HAVE_SHOPPING_EXISTS),
    NO_PRODUCT_NOT_FOUND(ERROR_PRODUCT_NOT_FOUND),
    CUSTOMER_EMAIL_IS_ALREADY_USED(ERROR_CUSTOMER_EMAIL_IS_ALREADY_USED),
    NO_ORDER_NOT_FOUND(ERROR_ORDER_NOT_FOUND),
    ORDER_IS_NOT_READY(ERROR_IS_NOT_READY),
    CUSTOMER_IS_ARCHIVED(ERROR_CUSTOMER_ARCHIVED),
    SHOPPING_CART_IS_NOT_FOUND(ERROR_SHOPPING_CART_NOT_FOUND);

    private final String template;

    @Override
    public String format(Object... args) {
        return String.format(template, args);
    }

}
